Features/key TTL
redis/redis-om-dotnet pull request #166
Opened 2022-07-31 12:11 UTC by shacharPash

Addresses #165

2022-08-02 18:38 UTC, slorello89 requested changes
Few things

1. We need async counterparts of everything we're doing here
2. Running 2 separate Executes is going to be nasty for performance because we're going to be running 2 round trips to Redis, so those need to be run in either a batch or transaction
3. We probably are going to want to use the native data structures of .NET to set expires / expiration times (TimeSpan,DateTime)
4. The methods need to be overloaded rather than have optional parameters added to them. Otherwise, it could be a breaking change to the binaries (not something we need to be super optimized on but its just something that users can run into).

2022-08-02 18:38 UTC, slorello89 commented on test/Redis.OM.Unit.Tests/CoreTests.cs
> +        public void ExpireTest()
Need an async test for this as well

2022-08-02 18:38 UTC, slorello89 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public string Insert(T item, long? expiry = null)
Need async counterpart

2022-08-02 18:38 UTC, slorello89 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public string Insert(T item, long? expiry = null)
Also, probably add this as an overload rather than an optional parameter, that way we won't break anyone dependent on the binaries overlaying the dll.

2022-08-02 18:38 UTC, slorello89 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        string Insert(T item, long? expiry = null);
Need async version, also change split this out as an overload

2022-08-02 18:38 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +        public static string Set(this IRedisConnection connection, object obj, long? expiry = null)
Needed in async version, also split this out as an overload

2022-08-02 18:38 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +            if (expiry != null)
This isn't ideal since we are going to be incurring 2 round trips to redis whenever someone tries to execute with an expiration, going to be terrible for performance, these should most likely be executed as part of a batch or transaction rather than as two separate command round trips to redis.

2022-08-02 18:38 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +        public static string Set(this IRedisConnection connection, object obj, long? expiry = null)
Probably want two overloads,

1: A true time to live - this might be a timespan rather than a number, could do both so could be three overloads
2: An expire time - this would probably be a date time or another long, either would probably work.

2022-08-02 18:38 UTC, slorello89 commented on test/Redis.OM.Unit.Tests/Serialization/PersonObject.cs
> +    public class Person
This shouldn't be necessary, there are Person objects elsewhere in the project, might just need to add an import statement to core tests.

2022-08-02 18:38 UTC, slorello89 commented on test/Redis.OM.Unit.Tests/CoreTests.cs
> +            Thread.Sleep(2000);
probably would want to use `await Task.Delay(2000)` instead of a Thread.Sleep, really not super material since this is just a test, but async over Thread.Sleep is commonly considered best practice.

2022-08-02 18:38 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +                connection.Execute("EXPIRE", obj.GetKey(), expiry.ToString());
`id` is generated above, so there shouldn't be a need to lean on StackExchange's GetKey method.

2022-08-02 18:38 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +using StackExchange.Redis;
Shouldn't need to import this outside the RedisConnection class.

2022-08-03 08:41 UTC, shacharPash commented
@slorello89 
Thanks for the comments!
Regarding section 2, what's the alternative?
Because in the JSON.SET and HSET commands I did not see that there is a built-in option of inserting a TTL in the command, which requires doing it in two commands.
I didn't quite understand what you meant when you said "those need to be run in either a batch or transaction".
In the meantime I'm working on the rest of the comments..

2022-08-03 16:18 UTC, VagyokC4 commented on src/Redis.OM/RedisCommands.cs
> +        public static string Set(this IRedisConnection connection, object obj, long? expiry = null)
2: for completeness, I could see the DateTime & the long overloads.  question, is this long a UnixTime() or UnixTimeMs().  Prefer the later.

2022-08-04 17:35 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +        public static string Set(this IRedisConnection connection, object obj, long? expiry = null)
Nice thing about a timespan is that you can always just convert it to ms - that's actually how they manage it in StackExchange.

2022-08-18 15:57 UTC, frostshoxx commented on test/Redis.OM.Unit.Tests/Serialization/PersonObject.cs
> +    public class Person
FYI: There are two places that have class Person defined right now:
- https://github.com/redis/redis-om-dotnet/blob/main/test/Redis.OM.Unit.Tests/RediSearchTests/Person.cs
- https://github.com/redis/redis-om-dotnet/blob/main/test/Redis.OM.Unit.Tests/SearchJsonTests/RedisJsonIndexTests.cs

2022-08-24 21:07 UTC, slorello89 approved these changes
LGTM 👍

2022-08-24 21:10 UTC, merged