connection string password bug
redis/redis-om-dotnet pull request #173
Opened 2022-08-06 22:31 UTC by rpf3

* fix a bug with the authenticated connection string generation
* add a .NET editorconfig

2022-08-06 22:53 UTC, rpf3 commented
@slorello89 I think I have the CI fix in the docker-compose file but I'm not sure the best practice for setting the Redis password in GitHub CI.  Is it fine to commit that in the yaml or is there a better way?

2022-08-06 22:54 UTC, rpf3 commented
closes #43

2022-08-08 12:45 UTC, slorello89 requested changes
I think what you're looking for here is an extra password-protected instance of redis - take a look at the docker folder, that ought to get you what you need.

2022-08-08 12:45 UTC, slorello89 commented on .editorconfig
> +root = true
File should be removed

2022-08-08 12:45 UTC, slorello89 commented on CONTRIBUTING.md
> +### Test Setup
Instead of this extra setup, you should just be able to add an extra redis instance in https://github.com/redis/redis-om-dotnet/blob/main/docker/docker-compose.yaml - that requires the password to test the case that requires a password.

2022-08-08 13:19 UTC, rpf3 commented on CONTRIBUTING.md
> +### Test Setup
So you mean just use the `PRIVATE_PASSWORD` environment variable in the docker-compose file correct?  How do we then push that down into the CI environment?

2022-08-31 21:25 UTC, rpf3 commented on CONTRIBUTING.md
> +### Test Setup
@slorello89 If I understood the documentation correctly, the idea was to just run a single Redis instance locally for the test suite, expecting that things like the sentinel tests would fail since that is defined in the docker-compose file.  Are you saying you want the private connection tests to follow this pattern?

2022-09-15 13:05 UTC, rpf3 commented on CONTRIBUTING.md
> +### Test Setup
@slorello89 any update on this?

2022-09-19 10:44 UTC, slorello89 approved these changes
needed some configuration updates in the docker-compose in order for the tests to work correctly in GH, that's all taken care of now. LGTM 👍 Thanks for the contribution @rpf3

2022-09-19 10:44 UTC, merged