Add nx/xx
redis/redis-om-dotnet pull request #206
Opened 2022-09-20 13:07 UTC by shacharPash

Related to #204

2022-09-20 13:09 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +        public static async Task<bool> JsonSetAsync(this IRedisConnection connection, string key, string path, string json, string when, TimeSpan? timeSpan = null)
`when` here should be an enum.

2022-09-20 13:10 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +        public static bool JsonSet(this IRedisConnection connection, string key, string path, object obj, string when, TimeSpan? timeSpan = null)
probably also want to have the equivalent overloads for the generic `Set` commands

2022-09-20 13:11 UTC, slorello89 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        string? InsertIfExist(T item, TimeSpan? timeSpan = null);
why the explicit overloads here vs the `when` condition in the generic commands?

2022-09-21 11:24 UTC, shacharPash commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        string? InsertIfExist(T item, TimeSpan? timeSpan = null);
I felt that this way is simpler to implement without breaking too many functions, but you can also use "when".

2022-09-21 14:22 UTC, shacharPash commented on src/Redis.OM/RedisCommands.cs
> +        public static async Task<bool> JsonSetAsync(this IRedisConnection connection, string key, string path, string json, string when, TimeSpan? timeSpan = null)
StackExchange already has such an Enum, I was debating whether to create a new one or use theirs, so for now I left it as a string.

2022-09-22 16:46 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +        public static async Task<bool> JsonSetAsync(this IRedisConnection connection, string key, string path, string json, string when, TimeSpan? timeSpan = null)
yeah, we can add a different enum here, I don't want to expose any data-types from SE that we don't have too.

2022-10-12 11:53 UTC, shacharPash commented on src/Redis.OM/RedisCommands.cs
> +        public static bool JsonSet(this IRedisConnection connection, string key, string path, object obj, string when, TimeSpan? timeSpan = null)
I bypassed Set and went straight from Insert to JsonSet. I think it's better that way because HSET doesn't have a When option

2022-10-21 11:40 UTC, slorello89 commented
@chayim - at this point, I've added to much to this PR to be an objective reviewer - can you please take a look?

2022-10-26 10:03 UTC, chayim commented on src/Redis.OM/RedisCommands.cs
> +            switch (when)
Why use a switch instead of an if/else? If/else is better for boolean values, as traditionally it's a single block passed to the compiler.

2022-10-26 10:03 UTC, chayim commented on src/Redis.OM/RedisCommands.cs
> +            switch (when)
Same question re if/else

2022-10-26 10:04 UTC, chayim commented on src/Redis.OM/RedisCommands.cs
> +                if (when == WhenKey.Always)
Can these be combined into a single branch? if when == && timespan.HasValue?

Branching multiple portions in the same if statement (rather than sub) is usually more performant.

2022-10-26 10:05 UTC, chayim commented on src/Redis.OM/RedisCommands.cs
> +                var kvps = obj.BuildHashSet();
kvps == key value properties?

2022-10-26 10:12 UTC, chayim commented on src/Redis.OM/RedisCommands.cs
> +        public static async Task<bool> JsonSetAsync(this IRedisConnection connection, string key, string path, string json, WhenKey when, TimeSpan? timeSpan = null)
I'm of two sides here.

On the client side, it's very clear that we have to expose based on name XX vs NX. But here.. I think it's a bad variable name. Ideally, to help users we could just name ifExists or similar. WDYT?

2022-10-26 10:12 UTC, chayim commented on src/Redis.OM/RedisCommands.cs
> +        /// <param name="timeSpan">the the timespan to set for your (TTL).</param>
Why timeSpan and not just seconds or evevn TTL? When I see timeSpan, as a user I assume I need seconds.. but maybe these are milliseconds?

I think the API should be more explict.

2022-10-26 10:13 UTC, chayim commented on src/Redis.OM/RedisCommands.cs
> +        /// <param name="timeSpan">the the timespan to set for your (TTL).</param>
Same for both when + timespan

2022-10-26 10:13 UTC, chayim commented on src/Redis.OM/RedisCommands.cs
> +        /// <param name="timeSpan">the the timespan to set for your (TTL).</param>
And again

2022-10-26 10:13 UTC, chayim commented on src/Redis.OM/RedisCommands.cs
> +                if (when == WhenKey.Exists)
Can this become a straight boolean?

2022-10-26 10:16 UTC, chayim requested changes
Logic works, some suggestions on perf and (perceived) API improvements for users.

2022-10-26 11:09 UTC, slorello89 reviewed
Thanks' @chayim - see my responses in this review.

2022-10-26 11:09 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +        /// <param name="timeSpan">the the timespan to set for your (TTL).</param>
There's a fair bit of precedent for .NET users for using a TimeSpan over straight up using seconds or millisecond in situations like this. TimeSpan's conveniently have a fair number of functions for simply producing these, e.g. TimeSpan.From(Millisecond/Hours/Day/Weeks etc. . .). Also when performing arithmetic on two [`DateTime`](https://learn.microsoft.com/en-us/dotnet/api/system.datetime?view=net-7.0) or [`DateTimeOffset`](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset?view=net-7.0) structs, the result is a timespan. So it's just easier (and what people are used to)

2022-10-26 11:09 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +        public static async Task<bool> JsonSetAsync(this IRedisConnection connection, string key, string path, string json, WhenKey when, TimeSpan? timeSpan = null)
The key here is that we are NOT in fact just exposing XX/NX, we are exposing whether we care to take any special action WRT to caring whether or not the object has existed [WhenKey](https://github.com/redis/redis-om-dotnet/pull/206/files/ab0330ad0b35b2e2aa07999121dcdde2c0f4e6bf#diff-af369e3f7cb66e0719c8d74cfb508bbcd6ee1b90b349582634babfde491c172d) uses the same semantics as the [When](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/Enums/When.cs) enum from StackExchange.Redis. We explicitly didn't want to expose that part of StackExchange.Redis' API, so we used a similarly named enum with the same semantics.

2022-10-26 11:09 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +        /// <param name="timeSpan">the the timespan to set for your (TTL).</param>
see above

2022-10-26 11:09 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +                var kvps = obj.BuildHashSet();
`kvps` in this content is referring to `KeyValuePair<TKey,TValue>` The response is actually a `Dictionary<TKey,TValue>` (equivalent of a HashMap/Dict) - but if you see it's usage in the foreach below, it's enumerator is being accessed, meaning we're effectively using it as a collection of `KeyValuePair<TKey,TValue>` (that's the type of enumerator a Dictionary exposes)

2022-10-26 11:09 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +            switch (when)
Using a switch here over an if/else because the semantic isn't to see whether or not the key exists, it's whether or not the user wants to add the `XX`/`NX` options (or their equivalent), you could use an if/else-if. The perf difference between an if/else-if and switch here is going to be negligible on a tiny set(might even be 0 depending on how the IL is compiled).

2022-10-26 11:09 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +            switch (when)
see above

2022-10-26 11:09 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +                if (when == WhenKey.Always)
it can, but you'd be adding an extra comparison:

```cs
if(when == WhenKey.Always && timeSpan.HasValue)
{
// set with timespan
}
else if (when == WhenKey.Always)
{
// set without timespan
}
```

The perf difference again would be negligible here. It's probably faster as is because in the case where `when == WhenKey.Always` you would always be performing two comparisons, versus with the if/else-if where you could be performing as many as 3. And then for the cases where `when != WhenKey.Always` in the current implementation you'd only perform 1 comparison, whereas with the if/else-if you'd be performing 3. Again, this is a super tiny thing, IMO it's better as is.

2022-10-26 11:09 UTC, slorello89 commented on src/Redis.OM/RedisCommands.cs
> +                if (when == WhenKey.Exists)
see above

2022-12-09 17:55 UTC, slorello89 approved these changes
LGTM 👍

2022-12-09 17:56 UTC, merged