Fix omnisharp warnings
redis/redis-om-dotnet pull request #21
Opened 2021-11-25 18:31 UTC by zhiburt

These fixes changing null to "" may only hide an inner issue.
But at least it may be seen here.

There are 2 different implementations of `IRedisConnection`
both in `Redis.OM` namespace.
I guess this must be addressed as well but I am not sure how.

https://github.com/redis/redis-om-dotnet/blob/main/src/Redis.OM.POC/RedisConnectionExtensions.cs#L10

2021-12-07 13:45 UTC, slorello89 commented on src/Redis.OM.POC/RespHelper.cs
> +                return "";
The redis protocol specifies that a -1 maps to null - so IMO this is correct - only thing I can think to do would be to update the return type from `Task<RedisReply>` -> `Task<RedisReply?>`

2021-12-07 13:46 UTC, slorello89 requested changes
Comment about -1 -> null mapping in the reply

2021-12-07 17:48 UTC, zhiburt commented on src/Redis.OM.POC/RespHelper.cs
> +                return "";
Seems good option.

2021-12-08 18:36 UTC, zhiburt commented on src/Redis.OM.POC/RespHelper.cs
> +                return "";
But actually it brings changes in public API.
Specifically this method. must be also made `Nullable`.
Which involves a list a changes is this OK then?

```c#
        Task<RedisReply> ExecuteAsync(string command, params string[] args);
```

2022-12-21 14:06 UTC, closed without merging