Adding Delete Document Stored Example
redis/redis-om-dotnet pull request #226
Opened 2022-10-05 06:26 UTC by rahul-s-bhatt

Closes #223 
My discord handle DevilRex#6421
Thank you.

2022-10-05 17:57 UTC, slorello89 requested changes
Looks really good @rahul-s-bhatt - one minor change (wrt to how ids are generated) that I think will make the example look a bit tidier :) Thanks so much for opening this!

2022-10-05 17:57 UTC, slorello89 commented on examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Program.cs
> +                Id = "Person1",
My preference here would to not set these Ids, it should work regardless because Redis OM will bind a ULID To the ID field. For this insert in particular (where we want to use the keyname to unlink) - we'd just pull the keyName out of the insertion and use that further down the pipe to delete the key.

2022-10-06 08:19 UTC, rahul-s-bhatt commented on examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Program.cs
> +                Id = "Person1",
@slorello89 Yes makes sense, thank you so much for the feedback.
Will try to do the requested changes and commit in few hours.

2022-10-06 11:12 UTC, slorello89 requested changes

2022-10-06 11:12 UTC, slorello89 commented on examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Program.cs
> +                Id = "Person1",
Hi @rahul-s-bhatt - yeah so now that you've removed the Ids from the other ones now you would save the key that comes out of the insertion (you can also drop the setting of the id here) - `var key = people.Insert(new Person . . . ` then down below on line  57 - you'd use the `key` var to unlink the person you'd just inserted - make sense?

2022-10-06 11:53 UTC, rahul-s-bhatt commented on examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Program.cs
> +                Id = "Person1",
@slorello89 Yes, wasn't aware about that.
Thanks for the feedback!
I have changed accordingly.

2022-10-06 16:51 UTC, slorello89 approved these changes
LGTM 👍 thanks for this - happy 🎃 hacktoberfest 🎃

2022-10-06 16:51 UTC, merged

2022-10-06 16:54 UTC, rahul-s-bhatt commented
> LGTM 👍 thanks for this - happy 🎃 hacktoberfest 🎃

@slorello89  Yes, thank you so much for the opportunity once again.
I really enjoyed learning this.

2022-10-06 17:04 UTC, SuzeShardlow commented
@rahul-s-bhatt thanks for collaborating with us! If you're a member of our Discord server (https://discord.gg/Redis), please let us know your handle so we can give you the `Hacktoberfest 2022` role 🙌🏽

2022-10-06 17:09 UTC, rahul-s-bhatt commented
@SuzeShardlow 

> @rahul-s-bhatt thanks for collaborating with us! If you're a member of our Discord server (https://discord.gg/Redis), please let us know your handle so we can give you the `Hacktoberfest 2022` role 🙌🏽

Hey @SuzeShardlow , My discord handle is RahulSBhatt#6421. 
Thank you for the role!

2022-10-11 13:28 UTC, SuzeShardlow commented
You're welcome!