Full-text search within an index example (#220)
redis/redis-om-dotnet pull request #230
Opened 2022-10-08 06:50 UTC by Jeevananthan-23

* Adding Full-text search within an index example 
*  Closes #220

2022-10-09 13:44 UTC, rtynski commented
My suggestions:
 - Full-Text_Search_within_an_Index to PascalCase (FullTextSearchWithinAnIndex)
 - RedisHelper to Helpers (as in Redis.OM.BasicMatchingQueries)
 - .sln file to delete (unspecifed @slorello89)

2022-10-09 13:51 UTC, rtynski commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Program.cs
> +            var movieWithFirstorDefault = _movieCollection.FirstOrDefault<Movie>(x => x.ImdbRating >5.5);
camelCase: movieWithFirstOrDefault

2022-10-09 13:51 UTC, rtynski commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Program.cs
> +            var getListofMovie = _movieCollection.Where(x => x.Year == 2003).ToList();
camelCase: getListOfMovie

2022-10-09 13:51 UTC, rtynski commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Program.cs
> +            var searchmixedLocals = new Movie();
camelCase: searchMixedLocals

2022-10-09 13:51 UTC, rtynski commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Program.cs
> +            //Sort the search result ascending use OrdreByDecending for DESC
typo: OrderByDescending

2022-10-09 13:51 UTC, rtynski commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Models/Movie.cs
> +    public enum Country
Separate file

2022-10-10 07:38 UTC, Jeevananthan-23 commented
Waiting for @slorello89 feedback so, I can make changes. Thanks!

2022-10-11 12:08 UTC, slorello89 approved these changes
looking pretty good @Jeevananthan-23 - couple minor items and then I think it's good to go.

2022-10-11 12:08 UTC, slorello89 commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Program.cs
> +            var _movieCollection = provider.RedisCollection<Movie>();
remove the underscore from the name (underscores are typically only associated with private members)

2022-10-11 12:08 UTC, slorello89 commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Program.cs
> +            var movieWithFirstorDefault = _movieCollection.FirstOrDefault<Movie>(x => x.ImdbRating >5.5);
```suggestion
            var movieWithFirstOrDefault = _movieCollection.FirstOrDefault<Movie>(x => x.ImdbRating > 5.5);
```

2022-10-11 12:08 UTC, slorello89 commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Program.cs
> +            var getListofMovie = _movieCollection.Where(x => x.Year == 2003).ToList();
```suggestion
            var getListOfMovies = _movieCollection.Where(x => x.Year == 2003).ToList();
```

2022-10-11 12:08 UTC, slorello89 commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Program.cs
> +            Console.WriteLine($"Title of the movie:{movieWithFirstorDefault.Title} and ImdbRating of the movie is {movieWithFirstorDefault.ImdbRating}");
```suggestion
            Console.WriteLine($"Title of the movie:{movieWithFirstOrDefault.Title} and ImdbRating of the movie is {movieWithFirstOrDefault.ImdbRating}");
```

2022-10-11 12:08 UTC, slorello89 commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Models/Awards.cs
> +        [Indexed(Sortable =true)]
```suggestion
        [Indexed(Sortable = true)]
```

2022-10-11 12:08 UTC, slorello89 commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Models/Awards.cs
> +        [Indexed(Sortable =true)]
```suggestion
        [Indexed(Sortable = true)]
```

2022-10-11 12:08 UTC, slorello89 commented on examples/Redis.OM.Full-Text_Search_within_an_Index/Program.cs
> +            ShowMovies("Year is 2003", getListofMovie);
```suggestion
            ShowMovies("Year is 2003", getListOfMovies);
```

2022-10-11 12:09 UTC, slorello89 requested changes
accidentally hit approve :)

2022-10-11 12:31 UTC, Jeevananthan-23 reviewed
Hi @slorello89, changes made please look into it.

2022-10-11 12:55 UTC, slorello89 commented
Hi @Jeevananthan-23 - I noticed some quirks in the namespaces (and the file/folder names) so I made some quick edits to those - should be good to go after this :)

2022-10-11 12:56 UTC, slorello89 approved these changes
LGTM 👍 thanks for the contribution! happy 🎃 Hacktoberfest 🎃

2022-10-11 13:09 UTC, merged