Quering string array example added #issue 221
redis/redis-om-dotnet pull request #231
Opened 2022-10-08 10:20 UTC by Ramin-Guliyev

2022-10-09 14:06 UTC, rtynski commented on examples/Redis.OM.QueryingStringsWithinArrays/Program.cs
> +Console.ReadKey();
Add new line

2022-10-09 14:11 UTC, rtynski commented
Proposal:
- Directory Helpers i Models (as in Redis.OM.BasicMatchingQueries)

2022-10-11 11:31 UTC, slorello89 requested changes
Looking pretty good @Ramin-Guliyev - just a couple of minor items and then I think we're good to go!

2022-10-11 11:31 UTC, slorello89 commented on examples/Redis.OM.QueryingStringsWithinArrays/Experience.cs
> +        return string.Join(" ", Skills.Skip(0));
calling `skip` with 0 is inert I think - so I'd say remove the Skip here.

2022-10-11 11:31 UTC, slorello89 commented on examples/Redis.OM.QueryingStringsWithinArrays/Program.cs
> +Console.ReadKey();
This is just personal preference, but I'd say remove the ReadKey at the end here and just let the program terminate when it's done.

2022-10-11 17:54 UTC, Ramin-Guliyev commented
@slorello89 I have done it. Please review again and merge :)

2022-10-11 20:22 UTC, slorello89 approved these changes
LGTM 👍 thanks for your contribution @Ramin-Guliyev happy 🎃 hacktoberfest 🎃 (will merge when CI is done)

2022-10-11 20:26 UTC, merged

2022-10-12 07:17 UTC, SuzeShardlow commented
@Ramin-Guliyev thanks for your PR!  If you are a member of our Discord server (https://discord.gg/redis), please let us know your handle so we can give you the `Hacktoberfest 2022` role :D