Create an Index and Store Documents
redis/redis-om-dotnet pull request #232
Opened 2022-10-09 14:01 UTC by zulander1

2022-10-09 14:21 UTC, rtynski commented
Suggestion:
- Delete a separate directory for the project (as other)
- All models to Models directory and in separate files.
- Create helpers for init data

2022-10-09 14:34 UTC, zulander1 commented
@rtynski what do you mean by Delete a separate directory for the project (as other)? Also, I've applied your suggestions

2022-10-09 16:20 UTC, rtynski commented
@zulander1 
FROM:
examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore.sln
examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore.csproj
examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/*.cs
TO:
examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore.sln (this file is I think optional)
examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore.csproj
examples/Redis.OM.CreateIndexStore/*.cs

Look: examples/Redis.OM.BasicMatchingQueries/

2022-10-10 13:43 UTC, SuzeShardlow commented
Thanks @zulander1, the reviewer for this will be @slorello89.

2022-10-10 13:44 UTC, SuzeShardlow commented
Closes #218 when merged.

2022-10-11 11:40 UTC, slorello89 requested changes
Hi @zulander1 - thanks for opening this! Just a few minor things then I think this will be good to go.

2022-10-11 11:40 UTC, slorello89 commented on examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Program.cs
> +var provider = new RedisConnectionProvider("redis://172.29.252.187:6379");
move this to `redis://localhost:6379` - for the moment I think the only assumption we'll make about connectivity is that they have a local instance of redis running.

2022-10-11 11:40 UTC, slorello89 commented on examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Program.cs
> +IList<Store> allStores = await stores.ToListAsync();
Move all these declarations from explicit -> var

2022-10-11 11:40 UTC, slorello89 commented on examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Program.cs
> +#region Setup provides,indexes and seed
remove the regions in this file :) there are limited circumstances where I'm pro-region but this file is much too small for that :)

2022-10-11 11:40 UTC, slorello89 commented on examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Models/Employee.cs
> +    internal record Store
move `Store` to it's own file. also change to public.

2022-10-11 11:40 UTC, slorello89 commented on examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Models/Employee.cs
> +    internal class Employee
change to public

2022-10-11 11:40 UTC, slorello89 commented on examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Models/Employee.cs
> +    internal enum EmploymentType
change to public.

2022-10-11 14:24 UTC, zulander1 commented
@slorello89 i've fixed everything as per your comments let me know if its okay 

thank's

2022-10-11 20:20 UTC, slorello89 approved these changes
LGTM 👍 thanks for the contribution! happy 🎃 hacktoberfest! 🎃

2022-10-11 20:21 UTC, merged

2022-10-12 07:22 UTC, SuzeShardlow commented
Hi @zulander1, thanks for your PR!  If you are a member of our Discord server (https://discord.gg/redis), please let us know your handle so we can give you the `Hacktoberfest 2022` role.  Thanks!

2022-10-12 12:15 UTC, zulander1 commented
@SuzeShardlow there you go zulander#3305

2022-10-12 12:24 UTC, SuzeShardlow commented
Thanks! I've assigned you the role in Discord 🙌🏽