adding bulkinsert support
redis/redis-om-dotnet pull request #246
Opened 2022-10-28 05:07 UTC by Jeevananthan-23

Close #238 - Adding a feature to Bulk Insert data into Redis with the help of pipelines.

2022-11-01 14:28 UTC, slorello89 requested changes

2022-11-01 14:28 UTC, slorello89 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        Task BulkInsert(IEnumerable<T> items);
1. This should yield the IDs of the items inserted into Redis. Not the full KeyNames, just the ids. That should be returned by the call to `Set` within the method.
2. This should just be named `Insert` and should just overload the regular behavior.
3. This should have an overload to accept a timespan so folks can do TTL with it.

2022-11-01 14:28 UTC, slorello89 commented on test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
> +            collection.Insert(new Person { Name = "John" });
bunch of little cosmetic things in here which distract from the crux of the review.

2022-11-01 14:29 UTC, slorello89 commented
@Jeevananthan-23 Thanks for submitting this, couple of comments about what the api should look like (also looks like a lot of stylistic stuff in the test class which distracts from what's going on in it).

2022-11-03 06:05 UTC, Jeevananthan-23 commented on test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
> +            collection.Insert(new Person { Name = "John" });
I'll fix this 👍 : )

2022-11-03 06:14 UTC, Jeevananthan-23 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        Task BulkInsert(IEnumerable<T> items);
@slorello89, I got your point here this method should return `List<string> ids` this must be the behavior of the method but the issue is with **Call to ** `Set`  within this method. Because the method is a `Task` typo which accepts it not a string type.

2022-11-04 16:20 UTC, slorello89 approved these changes
LGTM 👍 thanks for submitting this @Jeevananthan-23 :)

2022-11-04 16:21 UTC, merged