feature: Bulk Operations
redis/redis-om-dotnet pull request #278
Opened 2022-12-16 18:52 UTC by Jeevananthan-23

**Adding feature to Redis-om-dotnet where developers can perform Bulk Operations like Insert, Delete, and Update.**
- [ ] Bulk Insert - Insertion of records supports Hash and JSON docs(performance improvement `1000` records in an avg of `200ms`) https://github.com/Jeevananthan-23/redis-om-dotnet/issues/1#issue-1496163279

- [ ] Bulk Delete - Unlinks the keys from the Redis.  https://github.com/Jeevananthan-23/redis-om-dotnet/issues/3#issue-1496176859

- [ ]  Bulk Update - Update the records.  https://github.com/Jeevananthan-23/redis-om-dotnet/issues/2#issue-1496170149

- [ ] Closes #274, #261 , https://github.com/Jeevananthan-23/redis-om-dotnet/issues/1#issue-1496163279 🎉

2022-12-16 19:34 UTC, VagyokC4 commented
> * [x]  Bulk Insert - Insertion of records supports Hash and JSON docs(performance improvement `1000` records in an avg of `200ms`)

Question: Are these records added to the index, i.e. is this a real bulk import, or will these bulk records get indexed no problem?

2022-12-16 19:46 UTC, slorello89 commented
@VagyokC4 - If the index is already established, indexing them is part of the insertion, it happens synchronously and automatically, if the index has yet to be created, when the index IS created everything is indexed in the background.

2022-12-16 23:02 UTC, VagyokC4 commented
> @VagyokC4 - If the index is already established, indexing them is part of the insertion, it happens synchronously and automatically, if the index has yet to be created, when the index IS created everything is indexed in the background.

I've seen instances where I've had the index established, but I do a bulk insert, and those records are not in the index or searchable. I am forced to re-index the collection.

2022-12-17 05:31 UTC, Jeevananthan-23 commented
> > @VagyokC4 - If the index is already established, indexing them is part of the insertion, it happens synchronously and automatically, if the index has yet to be created when the index IS created everything is indexed in the background.
> 
> I've seen instances where I've had the index established, but I do a bulk insert, and those records are not in the index or searchable. I am forced to re-index the collection.

I think your uses case could be as follows : 
```cs
        [Fact]
        public async Task TestBulkInsertAsync()
        {
            var collection = new RedisCollection<Person>(_connection);
            var persons = new List<Person>() {
                new Person() { Name = "Alice", Age = 51, NickNames = new[] { "Ally", "Alie", "Al" } },
                new Person() { Name = "Robert", Age = 37, NickNames = new[] { "Bobby", "Rob", "Bob" } },
                new Person() { Name = "Jeeva", Age = 22, NickNames = new[] { "Jee", "Jeev", "J" } },
                new Person() { Name = "Martin", Age = 60, NickNames = new[] { "Mart", "Mat", "tin" } }
                };
            var keys = await collection.InsertAsync(persons); // performs JSON.SET create keys and emit the list of keys 

            var persons2 = new List<Person>() {
                new Person() { Name = "Alice", Age = 51, NickNames = new[] { "Ally", "Alie", "Al" }, IsEngineer = true },
                new Person() { Name = "Robert", Age = 37, NickNames = new[] { "Bobby", "Rob", "Bob" }, IsEngineer = false },
                new Person() { Name = "Jeeva", Age = 22, NickNames = new[] { "Jee", "Jeev", "J" }, DepartmentNumber = 201 },
                new Person() { Name = "Martin", Age = 60, NickNames = new[] { "Mart", "Mat", "tin" }, TagField = "Martin" }
                };

            var keys2 = await collection.InsertAsync(persons2); // create keys and emit the list of keys

            var people = collection.Where(x => x.NickNames.Contains("Bob") || x.NickNames.Contains("Alie")).ToList();
            Assert.Contains(people, x => x.Name == persons.First().Name);
            Assert.NotEqual(keys, keys2); // not performs any re-indexing because the keys are not the same.
        }
```

**The above test will answer your question and your intention here is to  perform the update the records so use UpdateMany in this case, Thanks!**

2022-12-21 14:32 UTC, slorello89 commented
> > @VagyokC4 - If the index is already established, indexing them is part of the insertion, it happens synchronously and automatically, if the index has yet to be created, when the index IS created everything is indexed in the background.
> 
> I've seen instances where I've had the index established, but I do a bulk insert, and those records are not in the index or searchable. I am forced to re-index the collection.

This sounds like it could be an indexing issue (ie your old index has something incompatible with the data in your index) - you can check to see if there were any indexing failures with FT.INFO

2023-01-03 03:45 UTC, Jeevananthan-23 commented
Hi @slorello89, looking forward to your feedback on this PR and will make changes accordingly. Thanks!

2023-01-03 13:23 UTC, slorello89 requested changes

2023-01-03 13:23 UTC, slorello89 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        void Update(IEnumerable<T> items);
IMO Sync Update is a bad idea, I wrote `Save` early on in Redis OM just in case someone needed something like this, but I don't think this should be propagated, as this is going to incur many round trips to Redis, I would just axe this and keep the Async (named `UpdateAsync`)

2023-01-03 13:23 UTC, slorello89 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        List<string> Insert(IEnumerable<T> items);
Ditto for these inserts, it's going to incur a ton of round trips to Redis so it's not really appropriate to have here. Also since you are changing the signature of `Insert` this would be a breaking change. Revert all the stuff for the bulk inserts, we'll have to live with the weird `Insert` vs `InsertAsync` name. Given that there's only one multi-variat insert I think that's fine.

2023-01-03 14:15 UTC, Jeevananthan-23 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        List<string> Insert(IEnumerable<T> items);
JSYK I'm using the [pipeline concept](https://stackexchange.github.io/StackExchange.Redis/PipelinesMultiplexers#pipelining) to get all requests onto the network immediately, eliminating most of the latency and reducing packets send to Redis. (Test is done for Sync operation and improved performance)

BTW adding some points for some improvements in the code 
* Adding `ArgumentNullException` for all the methods 
```csharp
  public void Update(IEnumerable<T> items)
        {
            if (items == null)
            {
                throw new ArgumentNullException("items cannot be null. Please provide a non-null list of items.");
            }
}
```
* Naming conversions for Bulk operation methods
```
BulkInsert()
BulkUpdate() or UpdateMany()
BulkDelete() or DeleteMany()
```
*Later I'll work on adding doc for all the bulk operations*

Thanks!

2023-01-03 14:31 UTC, slorello89 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        List<string> Insert(IEnumerable<T> items);
FYI @Jeevananthan-23 - the way you are trying to do this will cause deadlocks - so not a great idea - `Task.Wait` is fine if you have a very defined set of threads you are working with and you KNOW that your waits aren't going to seize all the threads that you need to run the tasks, but if you try to do this in a thread constrained environment (e.g. imagine your application only had 1 thread), the `Task.Wait`'s you'll accumulate can stop all the threads you need to run your tasks and deadlock your application. You might be interested to see how it's referred to in [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/PhysicalConnection.cs#LL971C17-L971C17) - but they take great pains to make sure their tasks in a detached context that will not be messed with, we make no such promises.

2023-01-03 17:45 UTC, Jeevananthan-23 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        List<string> Insert(IEnumerable<T> items);
@slorello89 I'll dive deep into it and make some test analysis through it. If possible guide me in this implementation to come up with a better solution.

2023-01-03 17:47 UTC, slorello89 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        List<string> Insert(IEnumerable<T> items);
As I mentioned - there isn't a good way to do this synchronously, so I'd just as soon remove the sync update/insert, can keep the sync delete because that's purely variadic.

2023-01-03 19:40 UTC, Jeevananthan-23 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        List<string> Insert(IEnumerable<T> items);
> BTW adding some points for some improvements in the code
> 
> * Adding `ArgumentNullException` for all the methods
> 
> ```cs
>   public void Update(IEnumerable<T> items)
>         {
>             if (items == null)
>             {
>                 throw new ArgumentNullException("items cannot be null. Please provide a non-null list of items.");
>             }
> }
> ```
> 
> * Naming conversions for Bulk operation methods
> 
> ```
> BulkInsert()
> BulkUpdate() or UpdateMany()
> BulkDelete() or DeleteMany()
> ```
> 
> _Later I'll work on adding doc for all the bulk operations_
> 
> Thanks!
@slorello89 if there is no way of doing it then fine. Any commands on those above points ?

2023-01-03 20:54 UTC, Jeevananthan-23 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        List<string> Insert(IEnumerable<T> items);
> FYI @Jeevananthan-23 - the way you are trying to do this will cause deadlocks - so not a great idea - `Task.Wait` is fine if you have a very defined set of threads you are working with and you KNOW that your waits aren't going to seize all the threads that you need to run the tasks, but if you try to do this in a thread constrained environment (e.g. imagine your application only had 1 thread), the `Task.Wait`'s you'll accumulate can stop all the threads you need to run your tasks and deadlock your application. You might be interested to see how it's referred to in [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/PhysicalConnection.cs#LL971C17-L971C17) - but they take great pains to make sure their tasks are in a detached context that will not be messed with, we make no such promises.

 `sync` makes the thread wait to complete, if it `multithreaded` application this is blocking call and user should aware of this process and go with `async`. As you mentioned before the `Save` is not used by over `SaveAsync` yes it's true but [ef core implementation also similar](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/providers/cosmos/limitations.md#azure-cosmos-db-sdk-limitations) so it's upto the user should understand the limitations to prevent deadlocks.

2023-01-04 03:28 UTC, Jeevananthan-23 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        List<string> Insert(IEnumerable<T> items);
@slorello89  adding one more solution to this issue using `GetAwaiter` instant of `Wait` may still cause deadlocks if it is used improperly. 

```csharp

public List<string> Insert(IEnumerable<T> items)
        {
            var tasks = new List<Task<string>>();
            foreach (var item in items.Distinct())
            {
                tasks.Add(((RedisQueryProvider)Provider).Connection.SetAsync(item));
            }

            Task.WhenAll(tasks).GetAwaiter();
            var result = tasks.Select(x => x.Result).ToList();
            return result;
        }

// calling Async but GetResult() is block the current thread
 public List<string> Insert(IEnumerable<T> items)
        {
            return InsertAsync(items).GetAwaiter().GetResult();
        }
```

2023-01-04 12:50 UTC, slorello89 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        List<string> Insert(IEnumerable<T> items);
@Jeevananthan-23 - fundamentally the issue is that running Async code from Sync code is an anti-pattern, and any properly sync patterns for this would be horrible on performance. This is why my conclusion has just been to remove the sync methods.

`InsertAsync`
`UpdateAsync`
`Delete`
`DeleteAsync`

Would be the names I would prefer, but since `Insert` is already the name, we ought to keep that (otherwise it will be a breaking change for people already using this)

2023-01-04 15:29 UTC, Jeevananthan-23 commented on src/Redis.OM/Searching/IRedisCollection.cs
> +        List<string> Insert(IEnumerable<T> items);
@slorello89 - Thanks for bearing with me a long conversation and pushing the feedback changes.

2023-01-13 13:35 UTC, slorello89 approved these changes
LGTM 👍

2023-01-13 13:36 UTC, merged