Async for bulk operation
redis/redis-om-dotnet pull request #338
Opened 2023-03-25 15:01 UTC by zulander1

Added Async suffix on async operations

2023-03-28 10:43 UTC, slorello89 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public async Task<List<string?>> InsertAsync(IEnumerable<T> items, WhenKey when, TimeSpan? timeSpan = null)
@zulander1 - what's the purpose of having the `List<string?>` version? A failure to create the document in Redis?

2023-03-28 12:26 UTC, zulander1 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public async Task<List<string?>> InsertAsync(IEnumerable<T> items, WhenKey when, TimeSpan? timeSpan = null)
None it was already there didn't want to change it ! I guess we can remove it ?

2023-03-28 12:30 UTC, slorello89 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public async Task<List<string?>> InsertAsync(IEnumerable<T> items, WhenKey when, TimeSpan? timeSpan = null)
yeah, pull it out I think (I don't think this one was actually here - it could just be the diff is acting weird?)

2023-03-28 15:49 UTC, zulander1 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public async Task<List<string?>> InsertAsync(IEnumerable<T> items, WhenKey when, TimeSpan? timeSpan = null)
so this https://github.com/redis/redis-om-dotnet/blob/b95ac2244ad5377fdf813564ca2b658e1e6c882b/src/Redis.OM/Searching/RedisCollection.cs#L648 and and https://github.com/redis/redis-om-dotnet/blob/b95ac2244ad5377fdf813564ca2b658e1e6c882b/src/Redis.OM/Searching/RedisCollection.cs#L679 are returning a list, however I am going to remove it ! thanks'

2023-03-28 16:47 UTC, zulander1 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public async Task<List<string?>> InsertAsync(IEnumerable<T> items, WhenKey when, TimeSpan? timeSpan = null)
Removed

2023-03-28 16:54 UTC, slorello89 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public async Task<List<string?>> InsertAsync(IEnumerable<T> items, WhenKey when, TimeSpan? timeSpan = null)
err I think you might of pushed to the wrong branch?

2023-03-28 17:03 UTC, zulander1 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public async Task<List<string?>> InsertAsync(IEnumerable<T> items, WhenKey when, TimeSpan? timeSpan = null)
Yeah you're right! I'll fix it this afternoon

2023-03-28 21:08 UTC, zulander1 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public async Task<List<string?>> InsertAsync(IEnumerable<T> items, WhenKey when, TimeSpan? timeSpan = null)
fixed !

2023-03-29 17:03 UTC, slorello89 requested changes

2023-03-29 17:03 UTC, slorello89 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public async Task InsertAsync(IEnumerable<T> items, TimeSpan timeSpan)
```suggestion
        public async Task<List<string>> InsertAsync(IEnumerable<T> items, TimeSpan timeSpan)
```

2023-03-29 17:03 UTC, slorello89 commented on src/Redis.OM/Searching/RedisCollection.cs
> +                return;
```suggestion
                return new List<string>();
```

2023-03-29 17:03 UTC, slorello89 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public async Task InsertAsync(IEnumerable<T> items, WhenKey when, TimeSpan? timeSpan = null)
Ok I see whats happening you are adding one with the `WhenKey` condition - I'm sorry I didn't catch that before. You were right! This needs to return a `List<string?>` because yes - there are cases where it would not have created anything - sorry about that - yeah just return the `List<string?>`

2023-03-29 17:33 UTC, zulander1 commented on src/Redis.OM/Searching/RedisCollection.cs
> +        public async Task InsertAsync(IEnumerable<T> items, WhenKey when, TimeSpan? timeSpan = null)
okay I've deleted the last commit, it should be back to the original

2023-03-29 17:42 UTC, slorello89 approved these changes
LGTM 👍

2023-03-29 17:42 UTC, merged