Adding Redis Index Info Command
redis/redis-om-dotnet pull request #40
Opened 2021-12-20 10:01 UTC by satish860

Changes are done to add Get the Redis Info. 

1. Added FT.INFO command and converts to Dictionary of strings
2. Added an async version of the same.
3. Added a Generic method to support the same.

2021-12-20 13:35 UTC, slorello89 requested changes
Hi @satish860 - this is a really solid contribution, my big overarching comment is that I'd rather not have an API reply with a Dictionary when there should be a strongly-typed alternative. The reply from `FT.INFO` should have a relatively defined response that we can map to. See: https://oss.redis.com/redisearch/Commands/#ftinfo

2021-12-20 13:35 UTC, slorello89 commented on src/Redis.OM/RediSearchCommands.cs
> +        internal static Dictionary<string, string> ToDictionary(RedisReply[] res)
Rather than returning a dictionary, we should return an `IndexInfo` object which someone can interrogate the fields of directly, I would say the parsing from a `RedisReply` should be handled directly in there.

2021-12-20 13:35 UTC, slorello89 commented on src/Redis.OM/RediSearchCommands.cs
> +        public static async Task<Dictionary<string, string>> GetIndexInfoasync<T>(this IRedisConnection connection)
Response type should be `IndexInfo` rather than a dictionary

2021-12-20 13:35 UTC, slorello89 commented on src/Redis.OM/RediSearchCommands.cs
> +        public static Dictionary<string, string> GetIndexInfo<T>(this IRedisConnection connection)
Response Type should be `IndexInfo` rather than a Dictionary

2021-12-20 13:35 UTC, slorello89 commented on src/Redis.OM/RediSearchCommands.cs
> +        public static async Task<Dictionary<string, string>> GetIndexInfoasync(
Response Type should be `IndexInfo` rather than a Dictionary

2021-12-20 13:35 UTC, slorello89 commented on src/Redis.OM/RediSearchCommands.cs
> +        public static Dictionary<string, string> GetIndexInfo(this IRedisConnection connection, string indexName)
Response Type should be `IndexInfo` rather than a Dictionary

2021-12-20 13:35 UTC, slorello89 commented on src/Redis.OM/RediSearchCommands.cs
> +using StackExchange.Redis;
Shouldn't need SE.R imported I wouldn't think?

2021-12-21 04:40 UTC, satish860 commented on src/Redis.OM/RediSearchCommands.cs
> +        public static async Task<Dictionary<string, string>> GetIndexInfoasync<T>(this IRedisConnection connection)
changed it .

2021-12-21 04:40 UTC, satish860 commented on src/Redis.OM/RediSearchCommands.cs
> +        public static async Task<Dictionary<string, string>> GetIndexInfoasync(
Changed it

2021-12-21 04:40 UTC, satish860 commented on src/Redis.OM/RediSearchCommands.cs
> +        public static Dictionary<string, string> GetIndexInfo(this IRedisConnection connection, string indexName)
Changed it.

2021-12-21 04:41 UTC, satish860 commented on src/Redis.OM/RediSearchCommands.cs
> +using StackExchange.Redis;
Removed the import

2021-12-21 04:41 UTC, satish860 commented on src/Redis.OM/RediSearchCommands.cs
> +        internal static Dictionary<string, string> ToDictionary(RedisReply[] res)
Added Redis Info Object and used the Index to take the property out from Redis Reply. 

I am wondering If I convert it to the dictionary and take it by the Key name so we can assign it to Redis Info.

2021-12-21 04:45 UTC, satish860 commented
@slorello89  Created a Redis info object with a single property to get an idea. There is one concern is the use of the RedisReply Array index rather than the proper key name for mapping.

So my idea is to convert the info command response to the dictionary of Key and RedisReply first and then move to the Redis Info object. Let me know your view.

2022-01-03 05:20 UTC, satish860 commented
Declining the Pull request as there is some conflict and not able to resolve the same.

2022-01-03 05:20 UTC, closed without merging