feat: Add the ability to compare existing index definitions to the projected one for a type
redis/redis-om-dotnet pull request #479
Opened 2024-09-02 09:34 UTC by abbottdev

Hi @slorello89,

This PR adds support to be able to have a _VERY_ simple mechanism for the consumer of the library to determine if they need to drop/recreate a given index.

I foresee people using this method like this pseudocode Index drop/create is async I believe, so the consumer would need to do their own polling to wait for the index to properly delete first but:
```csharp
var provider = new RedisConnectionProvider("redis://localhost:6379");
var definition = provider.Connection.GetIndexInfo(typeof(Customer));

if (definition.IndexDefinitionEquals(typeof(Customer)) == false)
{
    provider.Connection.DropIndex(typeof(Customer));
}

provider.Connection.CreateIndex(typeof(Customer));
```

Please forgive me that I've not raised an issue for this beforehand - I'm hoping this PR makes enough sense for us to discuss here.

Rather than making all the internals of `RedisIndex` visible, I've added an extension method that can be used to compare index definitions. 

Happy to discuss implementation/naming/test coverage but figure it's easier to discuss something visual.

2024-09-20 17:17 UTC, abbottdev commented
Bump @slorello89. Hope all's OK - not seen any issue activity on this repo for 2 months and this PR has been outstanding for a bit - any chance we can give the Redis .NET repo some love? ❤️ 

cc @benoitdion

2024-09-22 16:05 UTC, obradl commented
I support this functionality, it is much needed. I really enjoy Redis OM for .NET so far and this would be a nice improvement imo.

2024-09-25 19:50 UTC, slorello89 requested changes
@abbottdev - I think the only thing this really needs is to be able to answer this question directly from the connection. e.g. `IsModelCurrent`

```cs
provider.Connection.IsModelCurrent(typeof(Customer));
```

that way the library just takes care of everything for you without you having to fetch the index definition and then serialize the model yourself.

WDYT?

2024-10-03 07:16 UTC, VagyokC4 commented
> @abbottdev - I think the only thing this really needs is to be able to answer this question directly from the connection. e.g. `IsModelCurrent`
> 
> ```cs
> provider.Connection.IsModelCurrent(typeof(Customer));
> ```
> 
> that way the library just takes care of everything for you without you having to fetch the index definition and then serialize the model yourself.
> 
> WDYT?

Maybe even a method that keeps the index up to date
```cs
provider.Connection.UpdateIndex(typeof(Customer));
```
using the pattern below:

> ```cs
> var provider = new RedisConnectionProvider("redis://localhost:6379");
> var definition = provider.Connection.GetIndexInfo(typeof(Customer));
> 
> if (definition.IndexDefinitionEquals(typeof(Customer)) == false)
> {
>     provider.Connection.DropIndex(typeof(Customer));
> }
> 
> provider.Connection.CreateIndex(typeof(Customer));
> ```

2024-10-04 13:14 UTC, slorello89 approved these changes
@abbottdev - thanks for submitting this! I hope you don't mind, I pushed an update to add a method directly to the connection to check if the indexes match, I think it's good to go now, just awiting CI/CD

2024-10-04 13:15 UTC, merged

2024-10-05 06:49 UTC, VagyokC4 commented
> @VagyokC4 my big hangup with that approach is that I'm concerned about any implicit index dropping. Perhaps I'm overly cautious, but the drop / create has some implicit downtime (as the index rebuilds), so I'd rather not hide the drop.

I thought I saw somewhere there was an update index which doesn't drop it but merely patches it?