Enforced culture invariant compliance
redis/redis-om-dotnet pull request #52
Opened 2022-01-28 19:55 UTC by ecortese

This PR fixes all tests that fails when executed in an environment using a culture where the decimal number separator character isn't a dot char (e.g. it-IT, fr-FR, etc.).
For any failing test I've added an namesake one with the suffix "TestingInvariantCultureCompliance" where test runs on different process culture.

2022-02-17 13:19 UTC, slorello89 requested changes
@ecortese , thanks for submitting this, sorry it's taken a bit to get back to you, looks good, only comments I have are around how you are switching based on the full name of the class rather than it's type. Also probably want to account for nullable types as well in those same spots.

2022-02-17 13:19 UTC, slorello89 commented on src/Redis.OM/Common/ExpressionParserUtilities.cs
> +            return value.GetType().FullName switch
For all these here, probably do not want to do string comparisons with the fullname of the class, rather want to check against typeof(double), and so forth.

2022-02-17 13:19 UTC, slorello89 commented on src/Redis.OM/Searching/RedisQueryProvider.cs
> +                SYSTEMDOUBLETYPE => /*
same thing here, should be switched on the type rather than the fullname, it's also worth mentioning that the Nullable types will not necessarily comply either, may need to do a Nullable.GetUnderlying type and check the type before performing the switch, and do null-checks within.

2022-02-17 18:16 UTC, ecortese commented on src/Redis.OM/Common/ExpressionParserUtilities.cs
> +            return value.GetType().FullName switch
Hi @slorello89, yes I can see how much better is to use type comparison instead of name. Sincerelly I don't remember why I choiced to do so. I'll work on your change request.

2022-10-12 11:12 UTC, slorello89 approved these changes
@ecortese - apologies for taking so long to get back to you on this, I appreciate you bearing with me :) I pushed an update to manage the merge for the drift that's happened in the 8 months since you opened this - it looks good to go for me now - much appreciated.

2022-10-12 11:13 UTC, merged

2022-10-13 08:22 UTC, ecortese commented
@slorello89 no problem, have a nice day!