Add async version of DropIndexAndAssociatedRecords
redis/redis-om-dotnet pull request #60
Opened 2022-02-01 20:23 UTC by DanJRWalsh

2022-02-04 14:35 UTC, slorello89 requested changes
Thanks for submitting this PR, yeah I'm good with fixing DropIndexAsync as it's going to toss an exception out as if the index already exists, which sort of defeats the purpose of the boolean. 

Please add a functional test to validte this fix, should be fairly trivial to add.

However with the `DropIndexAndAsociatedRecords` I'm skeptical of adding an async version of that method, that method (and the index creation/deletion methods in general) are methods that really shouldn't be run in a situation where sync vs async code is important, so let's pull out the `DropIndexAndAssociatedRecordsAsync` method

2022-02-04 14:35 UTC, slorello89 commented on src/Redis.OM/RediSearchCommands.cs
> +        public static async Task<bool> DropIndexAndAssociatedRecordsAsync(this IRedisConnection connection, Type type)
I'm thinking we really don't need the `DropIndexAndAssociatedRecordsAsync` method as this is really something you shouldn't be doing in a situation where sync/async is of major importance 😂.

2022-02-04 14:47 UTC, DanJRWalsh commented on src/Redis.OM/RediSearchCommands.cs
> +        public static async Task<bool> DropIndexAndAssociatedRecordsAsync(this IRedisConnection connection, Type type)
@slorello89 That's fair but with that logic should we not remove `DropIndexAsync` then? I was adding it more for consistency than anything.

2022-02-04 15:17 UTC, danjrwalsh commented on src/Redis.OM/RediSearchCommands.cs
> +        public static async Task<bool> DropIndexAndAssociatedRecordsAsync(this IRedisConnection connection, Type type)
@slorello89 That's fair, I was trying to keep it consistent with `DropIndexAsync` and `CreateIndexAsync` but I have reverted the change. Will add a test for `DropIndexAsync` shortly. 

Speaking of pointless booleans, the same applies to `CreateIndex` and `CreateIndexAsync` (they will throw an exception if an index already exists). To keep it consistent, should the same exception handling be added to those two as well? If the exception being thrown is desired, then perhaps the return type should be changed since it will **always** be true if an exception is not thrown. The logic should be kept consistent across index creation and deletion methods, IMO.

2022-02-04 16:36 UTC, slorello89 commented on src/Redis.OM/RediSearchCommands.cs
> +        public static async Task<bool> DropIndexAndAssociatedRecordsAsync(this IRedisConnection connection, Type type)
Hi @DanJRWalsh Yeah, I think that's fair please by all means go ahead and add that.

2022-02-04 17:06 UTC, DanJRWalsh commented
@slorello89 Let me know if it needs anything else

2022-02-08 12:46 UTC, slorello89 approved these changes
LGTM 👍

2022-02-08 12:46 UTC, merged